pragma Singleton
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick

// Radial app-launcher: open state, the (persisted) app list, and edit ops.
// Toggled by the SUPER+A GlobalShortcut. apps persist to ~/.config/quickshell/apps.json.
Singleton {
    id: launcher
    property bool visible: false
    property bool editing: false
    property var apps: defaultApps

    // Which ring is showing: "apps" (configured apps), "windows" (open windows),
    // or "actions" (the focused window's actions around its icon). Each mode has
    // its own opening shortcut (see settings.shortcuts + shell.qml).
    property string mode: "apps"

    function open(m)       { mode = m || "apps"; actionApp = null; editing = false; visible = true }
    function close()       { visible = false; editing = false; actionApp = null }
    function toggleMode(m) { (visible && mode === (m || "apps")) ? close() : open(m) }
    function openSettings() { open("apps"); editing = true }   // tray "Settings…" entry

    // ---- per-app action menu (long-press) ----
    property var actionApp: null   // app whose action arc is showing, or null
    readonly property string gPlus:  ""   // desktop action
    readonly property string gClose: ""
    readonly property string gFloat: ""
    readonly property string gFull:  ""
    readonly property string gOpen:  ""
    readonly property string gKey:   "\uf084"   // custom shortcut action fallback glyph
    readonly property string gApp:   "\uf2d0"   // generic "app window" — fallback when a window/app has no resolvable icon

    // searchable icon-name library for the icon picker (generated by gen-icons.sh)
    property var icons: []
    FileView {
        path: Quickshell.shellDir + "/icons.json"
        watchChanges: true
        onFileChanged: reload()
        onLoaded: { try { launcher.icons = JSON.parse(text()) } catch (e) { console.log("Launcher: bad icons.json —", e) } }
    }

    // find the DesktopEntry matching an app (for its .desktop Actions)
    function findEntry(app) {
        var want = (app.wmClass || "").toLowerCase()
        var wantExec = ((app.exec && app.exec[0]) || "").split("/").pop().toLowerCase()
        var vals = DesktopEntries.applications.values
        for (var i = 0; i < vals.length; i++) {
            var e = vals[i]
            if (want && ((e.startupClass || "").toLowerCase() === want || (e.id || "").toLowerCase() === want)) return e
            var eExec = ((e.command && e.command[0]) || "").split("/").pop().toLowerCase()
            if (wantExec && eExec === wantExec) return e
        }
        return null
    }

    // actions = app's .desktop Actions (New Window, etc.) + window actions (Close/Float/…) when running
    // ALL candidate actions for an app (window-independent) — used by the settings
    // checklist. Each has a stable `id`. Desktop actions come from the .desktop file
    // (the app's real D-Bus/launch options); window actions are universal.
    function actionTemplates(app) {
        var out = []
        var e = findEntry(app)
        if (e && e.actions)
            for (var i = 0; i < e.actions.length; i++)
                out.push({ id: "d:" + e.actions[i].name, label: e.actions[i].name, glyph: gPlus, kind: "run", cmd: e.actions[i].command, group: "App" })
        out.push({ id: "w:close", label: "Close",      glyph: gClose, kind: "win", op: "close", group: "Window" })
        if (Compositor.canFloat) out.push({ id: "w:float", label: "Float",      glyph: gFloat, kind: "win", op: "float", group: "Window" })
        out.push({ id: "w:full",  label: "Fullscreen", glyph: gFull,  kind: "win", op: "full",  group: "Window" })
        var ca = app.customActions || []
        for (var k = 0; k < ca.length; k++)
            out.push({ id: "c:" + k, label: ca[k].label, icon: ca[k].icon, color: ca[k].color, glyph: gKey, kind: "keys", shortcut: ca[k].shortcut, group: "Custom" })
        return out
    }

    // actions shown in the arc: templates filtered by the per-app selection
    // (app.actionIds; undefined = all), window actions only when a window exists.
    function actionsFor(app) {
        var tmpl = actionTemplates(app)
        var ids = app.actionIds
        var running = windowFor(app) !== null
        var out = []
        for (var i = 0; i < tmpl.length; i++) {
            var t = tmpl[i]
            if (ids && t.kind !== "keys" && ids.indexOf(t.id) < 0) continue   // custom shortcuts always show
            if (t.kind === "win" && !running) continue
            out.push(t)
        }
        if (out.length === 0) out.push({ label: "Open", glyph: gOpen, kind: "launch" })
        return out
    }

    function runAction(app, a) {
        if (a.kind === "run") Quickshell.execDetached(a.cmd)
        else if (a.kind === "win") {
            var w = windowFor(app)
            if (w) {
                if (a.op === "close") Compositor.closeWindow(w)
                else if (a.op === "float") Compositor.toggleFloat(w)
                else if (a.op === "full") Compositor.fullscreen(w)
            }
        } else if (a.kind === "keys") {
            var wk = windowFor(app)
            if (wk && Compositor.canSendKeys) { var p = parseShortcut(a.shortcut); Compositor.sendKeys(wk, p.mods, p.key) }
            else launch(app)
        } else if (a.kind === "launch") launch(app)
        close()
    }

    // Replace apps[i] with a fresh object (new reference) so bindings that read
    // through Launcher.apps[idx] — the actions panel — actually re-evaluate.
    // (apps.slice() alone keeps the same element objects, so nested bindings go stale.)
    function _cloneApp(i) {
        var a = Object.assign({}, apps[i])
        if (a.customActions) a.customActions = a.customActions.slice()
        if (a.actionIds) a.actionIds = a.actionIds.slice()
        return a
    }
    function _commitApp(i, a) { apps[i] = a; apps = apps.slice(); save() }

    function setActionEnabled(i, id, on, allIds) {
        var a = _cloneApp(i)
        var cur = a.actionIds || allIds.slice()
        var idx = cur.indexOf(id)
        if (on && idx < 0) cur.push(id)
        else if (!on && idx >= 0) cur.splice(idx, 1)
        a.actionIds = cur
        _commitApp(i, a)
    }

    function parseShortcut(str) {
        var parts = (str || "").split("+").map(function (p) { return p.trim() }).filter(Boolean)
        if (parts.length === 0) return { mods: "", key: "" }
        var key = parts.pop()
        var mods = parts.map(function (m) { return m.toUpperCase() }).join(" ")
        return { mods: mods, key: key }
    }

    // ---- shortcut capture / validation ----
    readonly property var _modWords: ["ctrl", "control", "alt", "shift", "super", "meta"]
    // Qt key/modifiers (from a Keys.onPressed event) → "ctrl+shift+r" (Hyprland keysyms)
    function keyEventToShortcut(key, mods, text) {
        if (key === Qt.Key_Control || key === Qt.Key_Shift || key === Qt.Key_Alt
            || key === Qt.Key_Meta || key === Qt.Key_AltGr || key === Qt.Key_Super_L || key === Qt.Key_Super_R)
            return ""   // lone modifier — keep waiting
        var k = _keyName(key, text)
        if (!k) return ""
        var parts = []
        if (mods & Qt.ControlModifier) parts.push("ctrl")
        if (mods & Qt.AltModifier)     parts.push("alt")
        if (mods & Qt.ShiftModifier)   parts.push("shift")
        if (mods & Qt.MetaModifier)    parts.push("super")
        parts.push(k)
        return parts.join("+")
    }
    function _keyName(key, text) {
        var s = ({})
        s[Qt.Key_Return] = "return"; s[Qt.Key_Enter] = "return"; s[Qt.Key_Space] = "space"
        s[Qt.Key_Tab] = "tab"; s[Qt.Key_Escape] = "escape"; s[Qt.Key_Backspace] = "backspace"
        s[Qt.Key_Delete] = "delete"; s[Qt.Key_Home] = "home"; s[Qt.Key_End] = "end"
        s[Qt.Key_PageUp] = "prior"; s[Qt.Key_PageDown] = "next"
        s[Qt.Key_Left] = "left"; s[Qt.Key_Right] = "right"; s[Qt.Key_Up] = "up"; s[Qt.Key_Down] = "down"
        s[Qt.Key_Comma] = "comma"; s[Qt.Key_Period] = "period"; s[Qt.Key_Slash] = "slash"
        s[Qt.Key_Semicolon] = "semicolon"; s[Qt.Key_Minus] = "minus"; s[Qt.Key_Equal] = "equal"
        if (s[key] !== undefined) return s[key]
        if (key >= Qt.Key_F1 && key <= Qt.Key_F12) return "F" + (key - Qt.Key_F1 + 1)
        if (key >= Qt.Key_A && key <= Qt.Key_Z) return String.fromCharCode(97 + (key - Qt.Key_A))
        if (key >= Qt.Key_0 && key <= Qt.Key_9) return String.fromCharCode(48 + (key - Qt.Key_0))
        if (text && text.length === 1 && text.charCodeAt(0) > 32) return text.toLowerCase()
        return ""
    }
    function shortcutValid(str) {
        var p = parseShortcut(str)
        return p.key !== "" && _modWords.indexOf(p.key.toLowerCase()) < 0
    }
    function prettyShortcut(str) {
        return (str || "").split("+").map(function (p) {
            p = p.trim(); if (!p) return ""
            return p.length === 1 ? p.toUpperCase() : p.charAt(0).toUpperCase() + p.slice(1)
        }).filter(Boolean).join(" + ")
    }
    // reference-changing shortcut setter (for the recorder — display must refresh)
    function setCustomShortcut(i, j, val) {
        var a = _cloneApp(i)
        a.customActions[j] = Object.assign({}, a.customActions[j]); a.customActions[j].shortcut = val
        _commitApp(i, a)
    }
    function flush() { saveTimer.stop(); save() }
    function addCustomAction(i) {
        var a = _cloneApp(i)
        if (!a.customActions) a.customActions = []
        a.customActions.push({ label: "New action", shortcut: "ctrl+r", icon: "", color: "" })
        _commitApp(i, a)
    }
    // in-place (no reference change) so the field keeps focus while typing
    function setCustomField(i, j, key, val) { apps[i].customActions[j][key] = val; saveTimer.restart() }
    function setCustomIcon(i, j, icon) {
        var a = _cloneApp(i)
        a.customActions[j] = Object.assign({}, a.customActions[j]); a.customActions[j].icon = icon
        _commitApp(i, a)
    }
    function setCustomColor(i, j, color) {
        var a = _cloneApp(i)
        a.customActions[j] = Object.assign({}, a.customActions[j]); a.customActions[j].color = color
        _commitApp(i, a)
    }
    function removeCustomAction(i, j) {
        var a = _cloneApp(i)
        a.customActions.splice(j, 1)
        _commitApp(i, a)
    }

    // ---- appearance settings (persisted separately) ----
    readonly property var defaultSettings: ({
        accent: "#e44854",     // radish red (brand) — hover sector (selected-icon background)
        bg: "#c9d8ef",         // donut band colour (independent of accent)
        iconSize: 54,
        ringRadius: 150,
        dim: 0.28,
        wheelOpacity: 0.96,
        showLabels: true,
        thumbnails: false,     // live window thumbnail when scrolling a multi-window app
        followOutside: false,  // sector tracks the cursor across the whole screen, off the ring too
        holdMs: 450,
        persistBinds: true,    // true: write binds to launcher-binds.conf (survives reload); false: apply live only, no config edits
        shortcutsEnabled: true, // master on/off for RadiAll-managed ring keybinds (off = open via tray / your own radiall bind)
        // per-mode opening shortcuts (registered with Hyprland at runtime)
        shortcuts: ({ apps: "super+a", windows: "super+w", actions: "super+d" })
    })
    property var settings: defaultSettings

    FileView {
        id: settingsStore
        path: Quickshell.shellDir + "/launcher-settings.json"
        onLoaded: {
            try {
                var s = Object.assign({}, launcher.defaultSettings, JSON.parse(text()))
                s.shortcuts = Object.assign({}, launcher.defaultSettings.shortcuts, s.shortcuts || {})
                launcher.settings = s
            }
            catch (e) { console.log("Launcher: bad settings.json —", e) }
            launcher.applyShortcuts()
        }
        onLoadFailed: (err) => { saveSettings(); applyShortcuts() }
    }
    function saveSettings() { settingsStore.setText(JSON.stringify(launcher.settings, null, 2)) }
    Timer { id: setTimer; interval: 250; onTriggered: launcher.saveSettings() }
    function setSetting(key, val) {
        var s = Object.assign({}, launcher.settings)   // reassign → live bindings update
        s[key] = val
        launcher.settings = s
        setTimer.restart()
    }
    function resetSettings() { settings = Object.assign({}, defaultSettings); saveSettings(); applyShortcuts() }

    // ---- per-mode opening shortcuts ----
    // Persisted in a Hyprland config file we own (sourced by keybinds.conf), so
    // they survive `hyprctl reload`. On change we ALSO apply immediately with
    // `hyprctl keyword` so there's no wait for a reload.
    FileView {
        id: bindsFile
        path: Quickshell.env("HOME") + "/.config/hypr/launcher-binds.conf"
    }
    function writeBindsFile() {
        var sc = settings.shortcuts || {}
        var lines = ["# Managed by the Quickshell launcher settings. Sourced by keybinds.conf."]
        var modes = ["apps", "windows", "actions"]
        for (var i = 0; i < modes.length; i++) {
            var p = parseShortcut(sc[modes[i]])
            if (p.key) lines.push("bind = " + p.mods + ", " + p.key + ", global, launcher:" + modes[i])
        }
        bindsFile.setText(lines.join("\n") + "\n")
    }
    // Runtime-only mode leaves the sourced file empty (adds nothing to the
    // Hyprland config) and applies the binds live instead.
    function clearBindsFile() {
        bindsFile.setText("# RadiAll: keybinds applied at runtime; Hyprland config left untouched.\n")
    }
    function applyRuntimeBinds() {
        var sc = settings.shortcuts || {}
        var modes = ["apps", "windows", "actions"]
        for (var i = 0; i < modes.length; i++) _hyprBind(modes[i], sc[modes[i]])
    }
    function _hyprBind(mode, str) {
        var p = parseShortcut(str)
        if (!p.key) return
        var kb = p.mods + "," + p.key
        Quickshell.execDetached(["sh", "-c",
            "hyprctl keyword unbind '" + kb + "'; "
            + "hyprctl keyword bind '" + kb + ",global,launcher:" + mode + "'"])
    }
    function _hyprUnbind(str) {
        var p = parseShortcut(str)
        if (p.key) Quickshell.execDetached(["hyprctl", "keyword", "unbind", p.mods + "," + p.key])
    }
    // Reconcile the compositor keybinds with current settings. Disabled → drop
    // every ring bind (nothing grabbed). persistBinds → keep the sourced file
    // (survives reload); else empty it. Live binds are always (re)applied so a
    // change takes effect without waiting for a reload.
    function clearAllBinds() {
        var sc = settings.shortcuts || {}
        var modes = ["apps", "windows", "actions"]
        for (var i = 0; i < modes.length; i++) _hyprUnbind(sc[modes[i]])
        clearBindsFile()
    }
    function applyShortcuts() {
        if (!Compositor.canManageKeybinds) return    // non-Hyprland: bind `radiall --apps` in your compositor instead
        if (!settings.shortcutsEnabled) { clearAllBinds(); return }
        if (settings.persistBinds) writeBindsFile()
        else clearBindsFile()
        applyRuntimeBinds()
    }
    function setPersistBinds(v) { setSetting("persistBinds", v); applyShortcuts() }
    function setShortcutsEnabled(v) { setSetting("shortcutsEnabled", v); applyShortcuts() }
    function setShortcut(mode, str) {
        var old = (settings.shortcuts || {})[mode]
        var sc = Object.assign({}, settings.shortcuts); sc[mode] = str
        setSetting("shortcuts", sc)
        if (settings.persistBinds) writeBindsFile()   // persist for next reload (skipped in runtime-only mode)
        if (old && old !== str) _hyprUnbind(old)    // drop the previous key now
        _hyprBind(mode, str)                        // apply the new key now
    }

    // Runtime-only binds are wiped by `hyprctl reload`; re-apply them each time
    // Hyprland reloads its config. (Persistent mode needs nothing — the sourced
    // file is re-read automatically.)
    Connections {
        target: Hyprland
        function onRawEvent(event) {
            if (event.name === "configreloaded" && Compositor.canManageKeybinds && launcher.settings.shortcutsEnabled && !launcher.settings.persistBinds)
                launcher.applyRuntimeBinds()
        }
    }

    // installed apps (for the picker), auto-mapped to our app schema
    readonly property var installed: {
        var out = []
        var vals = DesktopEntries.applications.values
        for (var i = 0; i < vals.length; i++) {
            var e = vals[i]
            if (e.noDisplay) continue
            out.push({ name: e.name, icon: e.icon || "application-x-executable",
                       exec: e.command && e.command.length ? e.command : [e.id],
                       wmClass: e.startupClass || e.id })
        }
        out.sort((a, b) => a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1)
        return out
    }

    // seeded on first run (when apps.json doesn't exist yet)
    readonly property var defaultApps: [
        { name: "Firefox",  icon: "firefox",            exec: ["firefox"],  wmClass: "firefox" },
        { name: "Chromium", icon: "/usr/share/icons/hicolor/256x256/apps/chromium.png", exec: ["chromium"], wmClass: "chromium" },
        { name: "VS Code",  icon: "visual-studio-code", exec: ["code"],     wmClass: "Code" },
        { name: "Obsidian", icon: "/usr/share/icons/hicolor/512x512/apps/obsidian.png", exec: ["obsidian"], wmClass: "obsidian" },
        { name: "Terminal", icon: "kitty",              exec: ["kitty"],    wmClass: "kitty" },
        { name: "Files",    icon: "org.xfce.thunar",    exec: ["thunar"],   wmClass: "thunar" },
        { name: "GIMP",     icon: "gimp",               exec: ["gimp-3.2"], wmClass: "gimp" },
        { name: "mpv",      icon: "mpv",                exec: ["mpv"],      wmClass: "mpv" }
    ]

    // ---- persistence ----
    FileView {
        id: store
        path: Quickshell.shellDir + "/apps.json"
        onLoaded: {
            try {
                var a = JSON.parse(text())
                if (Array.isArray(a) && a.length) launcher.apps = a
            } catch (e) { console.log("Launcher: bad apps.json —", e) }
        }
        onLoadFailed: (err) => save()   // no file yet → seed with defaults
    }
    function save() { store.setText(JSON.stringify(launcher.apps, null, 2)) }
    Timer { id: saveTimer; interval: 400; onTriggered: launcher.save() }

    // ---- edit ops ----
    // in-place field edit (no array reassignment → keeps editor field focus)
    function setField(i, key, val) { apps[i][key] = val; saveTimer.restart() }
    function commit() { apps = apps.slice(); save(); editing = false }  // refresh wheel + persist

    function addApp() {
        apps.push({ name: "New App", icon: "application-x-executable", exec: [""], wmClass: "" })
        apps = apps.slice(); save()
    }
    function addAppObj(o) {
        apps.push({ name: o.name, icon: o.icon, exec: o.exec.slice(), wmClass: o.wmClass || "" })
        apps = apps.slice(); save()
    }
    function removeApp(i) { apps.splice(i, 1); apps = apps.slice(); save() }
    function moveApp(i, dir) {
        var j = i + dir
        if (j < 0 || j >= apps.length) return
        var t = apps[i]; apps[i] = apps[j]; apps[j] = t
        apps = apps.slice(); save()
    }

    // ---- launch / focus ----
    function launch(app) { Quickshell.execDetached(app.exec) }

    // ---- multi-window: scroll on an app to pick which of its windows to target ----
    property var winSel: ({})   // wmClass(lc) -> chosen window index (transient, not persisted)

    // ring contents by mode. "apps" returns `apps` without touching toplevels, so
    // it only rebuilds when apps change — not on every window open/close.
    readonly property var ringModel: {
        if (mode === "windows") return windowRing
        if (mode === "actions") return actionRing
        return apps
    }

    // "windows" mode: one entry per open window.
    readonly property var windowRing: {
        var tls = Compositor.windows
        var out = []
        for (var i = 0; i < tls.length; i++) {
            var t = tls[i]
            var cls = classOf(t)
            out.push({ name: windowTitle(t) || cls, icon: iconForClass(cls),
                       wmClass: cls, _win: t, isWindow: true })
        }
        out.sort(function (a, b) {                 // group windows of the same app together
            var ca = a.wmClass.toLowerCase(), cb = b.wmClass.toLowerCase()
            if (ca !== cb) return ca < cb ? -1 : 1
            return a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1
        })
        return out
    }

    // "actions" mode: the focused window's app, and its actions as ring items.
    // Merge the matching CONFIGURED app (by wmClass) so its custom actions,
    // per-app action selection, and chosen icon reach the ring — the bare window
    // object has none of those.
    readonly property var focusedApp: {
        void Compositor.windows
        var t = Compositor.activeWindow
        if (!t) return null
        var cls = classOf(t)
        if (!cls) return null
        var cfg = null
        var want = cls.toLowerCase()
        for (var i = 0; i < apps.length; i++)
            if ((apps[i].wmClass || "").toLowerCase() === want) { cfg = apps[i]; break }
        var out = { name: windowTitle(t) || cls,
                    icon: (cfg && cfg.icon) || iconForClass(cls),
                    wmClass: cls, _win: t, isWindow: true }
        if (cfg) { out.customActions = cfg.customActions; out.actionIds = cfg.actionIds }
        return out
    }
    readonly property var actionRing: {
        var app = focusedApp
        if (!app) return []
        var acts = actionsFor(app)
        var out = []
        for (var i = 0; i < acts.length; i++) {
            var a = acts[i]
            out.push(Object.assign({}, a, { name: a.label, icon: a.icon || "",
                                            isAction: true, _app: app }))
        }
        return out
    }

    // Unified activation from the wheel: run an action in "actions" mode,
    // otherwise focus/launch the app or window.
    function activateItem(item, button) {
        if (!item) { close(); return }
        if (item.isAction) { runAction(item._app, item); return }   // runAction closes
        close()
        if (button === Qt.RightButton && !item.isWindow) launch(item)
        else activate(item)
    }
    // Resolve an icon name/path to an Image source that WILL load. Absolute path →
    // file://. Otherwise resolve against the icon theme in "check" mode, so a missing
    // icon yields "" (caller shows a monogram) instead of iconPath's purple
    // missing-texture square; fall back to the generic app icon when the theme has it.
    function iconSource(icon) {
        icon = icon || ""
        if (icon === "") return ""
        if (icon.charAt(0) === "/") return "file://" + icon
        var p = Quickshell.iconPath(icon, true)
        return p !== "" ? p : Quickshell.iconPath("application-x-executable", true)
    }
    // a toplevel's app class: appId (reliably populated) else the IPC class
    function classOf(t) { return Compositor.appId(t) }
    // Best icon NAME for a window class. Auto-discovers the matching .desktop entry —
    // exact StartupWMClass/id, then a fuzzy heuristic for apps whose class ≠ id (e.g.
    // window "orca" vs entry "stably-orca") — and uses its Icon=. Returns the class
    // itself as a last guess; iconSource verifies it actually resolves.
    function iconForClass(cls) {
        var c = (cls || "").toLowerCase()
        if (c === "") return ""
        for (var i = 0; i < apps.length; i++)
            if ((apps[i].wmClass || "").toLowerCase() === c) return apps[i].icon
        var vals = DesktopEntries.applications.values
        for (var j = 0; j < vals.length; j++) {
            var e = vals[j]
            if ((e.startupClass || "").toLowerCase() === c || (e.id || "").toLowerCase() === c)
                return e.icon || cls
        }
        var h = DesktopEntries.heuristicLookup(c)
        if (h && h.icon) return h.icon
        return cls
    }

    function windowsFor(app) {
        var out = []
        if (!app) return out
        if (app.isWindow) { if (app._win) out.push(app._win); return out }   // ring entry IS a window
        var want = (app.wmClass || "").toLowerCase()
        if (want === "") return out
        var tls = Compositor.windows
        for (var i = 0; i < tls.length; i++) {
            var t = tls[i]
            if (Compositor.appId(t).toLowerCase() === want) out.push(t)
        }
        return out
    }
    function selectedWindowIndex(app) {
        var ws = windowsFor(app)
        if (ws.length === 0) return -1
        var idx = winSel[(app.wmClass || "").toLowerCase()] || 0
        return idx >= ws.length ? 0 : idx
    }
    function windowFor(app) {
        if (app && app.isWindow) return app._win
        var ws = windowsFor(app)
        var idx = selectedWindowIndex(app)
        return idx < 0 ? null : ws[idx]
    }
    function cycleWindow(app, dir) {
        var ws = windowsFor(app)
        if (ws.length <= 1) return
        var key = (app.wmClass || "").toLowerCase()
        var idx = ((winSel[key] || 0) + dir) % ws.length
        if (idx < 0) idx += ws.length
        var s = Object.assign({}, winSel); s[key] = idx; winSel = s   // reassign → bindings update
    }
    function firstRunningIndex() {
        void Compositor.windows
        var m = ringModel
        for (var i = 0; i < m.length; i++)
            if (windowsFor(m[i]).length > 0) return i
        return 0
    }
    function windowTitle(w) { return Compositor.title(w) }

    // left-click: focus existing window (jumps to its workspace), else launch
    function activate(app) {
        var w = windowFor(app)
        if (w) Compositor.activate(w)
        else launch(app)
    }
}
